import type { Category, Product, Order, CustomerMember } from '../types/pos';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Minuman & Kopi', description: 'Es Kopi Susu Gula Aren, Espresso, Latte, & Signature Coffee', icon: 'Coffee' },
  { id: 'cat-2', name: 'Makanan Utama & Toast', description: 'Roti Bakar Kaya, Toast Smoked Beef, & Butter Croissant', icon: 'Utensils' },
  { id: 'cat-3', name: 'Non-Kopi & Teh', description: 'Matcha Uji, Chocolate Hazelnut, & Artisan Earl Grey Tea', icon: 'CupSoda' },
  { id: 'cat-4', name: 'Snack & Dessert', description: 'Brewly Mix Platter, Croffle Caramel, & Brownie Almond', icon: 'IceCream' },
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. Minuman & Kopi
  {
    id: 'prod-1',
    sku: 'PRD-001',
    name: 'Es Kopi Susu Gula Aren Signature',
    description: 'Espresso arabika dipadukan dengan susu segar dan gula aren asli',
    price: 22000,
    costPrice: 9000,
    stock: 50,
    minStock: 10,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/es-kopi-susu-gula-aren.jpg',
  },
  {
    id: 'prod-2',
    sku: 'PRD-002',
    name: 'Kopi Tubruk Arabika Gayo',
    description: 'Seduhan biji kopi murni khas Gayo Aceh dengan aroma rempah harum',
    price: 18000,
    costPrice: 6000,
    stock: 40,
    minStock: 10,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/kopi-tubruk-arabika-gayo.jpg',
  },
  {
    id: 'prod-3',
    sku: 'PRD-003',
    name: 'Iced Caramel Macchiato',
    description: 'Espresso double shot dengan sirup karamel gurih dan foam lembut',
    price: 32000,
    costPrice: 14000,
    stock: 35,
    minStock: 8,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/iced-caramel-macchiato.jpg',
  },
  {
    id: 'prod-4',
    sku: 'PRD-004',
    name: 'Spanish Latte Creamy',
    description: 'Espresso segar dipadukan dengan susu kental manis gurih',
    price: 28000,
    costPrice: 11000,
    stock: 30,
    minStock: 5,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/spanish-latte-creamy.jpg',
  },
  {
    id: 'prod-5',
    sku: 'PRD-005',
    name: 'Americano Iced Double Shot',
    description: 'Double shot espresso murni disajikan dingin dengan es batu',
    price: 20000,
    costPrice: 7000,
    stock: 45,
    minStock: 10,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/americano-iced.jpg',
  },
  {
    id: 'prod-6',
    sku: 'PRD-006',
    name: 'Avocado Coffee Float',
    description: 'Jus alpukat mentega segar dengan es krim vanilla dan shot espresso',
    price: 35000,
    costPrice: 15000,
    stock: 25,
    minStock: 5,
    categoryId: 'cat-1',
    categoryName: 'Minuman & Kopi',
    image: '/products/avocado-coffee-float.jpg',
  },

  // 2. Non-Kopi & Teh
  {
    id: 'prod-7',
    sku: 'PRD-007',
    name: 'Matcha Latte Creamy Uji',
    description: 'Bubuk matcha jepang pilihan diseduh dengan susu segar hangat',
    price: 30000,
    costPrice: 12000,
    stock: 3,
    minStock: 5,
    categoryId: 'cat-3',
    categoryName: 'Non-Kopi & Teh',
    image: '/products/matcha-latte-creamy.jpg',
  },
  {
    id: 'prod-8',
    sku: 'PRD-008',
    name: 'Iced Chocolate Hazelnut',
    description: 'Cokelat pekat ala belgian dengan aroma sirup hazelnut gurih',
    price: 28000,
    costPrice: 11000,
    stock: 25,
    minStock: 5,
    categoryId: 'cat-3',
    categoryName: 'Non-Kopi & Teh',
    image: '/products/iced-chocolate-hazelnut.jpg',
  },
  {
    id: 'prod-9',
    sku: 'PRD-009',
    name: 'Artisan Earl Grey Lemon Tea',
    description: 'Teh hitam beraroma bergamot dengan perasan jeruk lemon segar',
    price: 22000,
    costPrice: 8000,
    stock: 30,
    minStock: 5,
    categoryId: 'cat-3',
    categoryName: 'Non-Kopi & Teh',
    image: '/products/artisan-earl-grey.jpg',
  },

  // 3. Makanan Utama & Toast
  {
    id: 'prod-10',
    sku: 'PRD-010',
    name: 'Roti Bakar Kaya Butter Toast',
    description: 'Roti tawar tebal dipanggang dengan srikaya legit dan potongan butter',
    price: 24000,
    costPrice: 9000,
    stock: 20,
    minStock: 5,
    categoryId: 'cat-2',
    categoryName: 'Makanan Utama & Toast',
    image: '/products/roti-bakar-kaya.jpg',
  },
  {
    id: 'prod-11',
    sku: 'PRD-011',
    name: 'Croissant Butter Classic',
    description: 'Pastry butter perancis yang renyah di luar dan lembut di dalam',
    price: 26000,
    costPrice: 11000,
    stock: 18,
    minStock: 5,
    categoryId: 'cat-2',
    categoryName: 'Makanan Utama & Toast',
    image: '/products/croissant-butter.jpg',
  },
  {
    id: 'prod-12',
    sku: 'PRD-012',
    name: 'Sandwich Smoked Beef & Cheese',
    description: 'Sandwich isi daging sapi asap dengan lelehan keju mozarella',
    price: 36000,
    costPrice: 18000,
    stock: 0,
    minStock: 5,
    categoryId: 'cat-2',
    categoryName: 'Makanan Utama & Toast',
    image: '/products/sandwich-smoked-beef.jpg',
  },

  // 4. Snack & Dessert
  {
    id: 'prod-13',
    sku: 'PRD-013',
    name: 'Brewly Supreme Mix Platter',
    description: 'Kombinasi kentang goreng, sosis panggang, chicken nugget, & onion rings dengan saus cocolan',
    price: 38000,
    costPrice: 16000,
    stock: 30,
    minStock: 5,
    categoryId: 'cat-4',
    categoryName: 'Snack & Dessert',
    image: '/products/brewly-supreme-platter.jpg',
  },
  {
    id: 'prod-14',
    sku: 'PRD-014',
    name: 'Crispy Croffle Caramel Glaze',
    description: 'Croffle renyah disiram saus karamel lezat dan taburan gula halus',
    price: 25000,
    costPrice: 10000,
    stock: 20,
    minStock: 5,
    categoryId: 'cat-4',
    categoryName: 'Snack & Dessert',
    image: '/products/crispy-croffle.jpg',
  },
  {
    id: 'prod-15',
    sku: 'PRD-015',
    name: 'Pisang Goreng Keju Cokelat Crispy',
    description: 'Pisang tanduk goreng tepung renyah bertabur keju cheddar parut dan susu kental manis cokelat',
    price: 22000,
    costPrice: 8000,
    stock: 20,
    minStock: 5,
    categoryId: 'cat-4',
    categoryName: 'Snack & Dessert',
    image: '/products/pisang-goreng-cokelat.jpg',
  },
  {
    id: 'prod-16',
    sku: 'PRD-016',
    name: 'Fudgy Chocolate Brownie Almond',
    description: 'Brownie cokelat pekat bertabur irisan almond renyah',
    price: 22000,
    costPrice: 9000,
    stock: 15,
    minStock: 5,
    categoryId: 'cat-4',
    categoryName: 'Snack & Dessert',
    image: '/products/fudgy-brownie.jpg',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    // Andi Pratama — 20 Agu 2026, 17:26 (paling baru)
    id: 'ord-101',
    invoiceNumber: 'INV-982101',
    customerName: 'Andi Pratama',
    paymentMethod: 'CASH',
    subtotal: 48000,
    discountPercent: 0,
    discountAmount: 0,
    taxRatePercent: 11,
    taxAmount: 5280,
    totalAmount: 53280,
    paidAmount: 100000,
    changeAmount: 46720,
    status: 'COMPLETED',
    createdAt: '2026-08-20T17:26:00+07:00',
    items: [
      { id: 'item-101-1', productId: 'prod-1', productName: 'Es Kopi Susu Gula Aren Signature', quantity: 1, unitPrice: 22000, subtotal: 22000 },
      { id: 'item-101-2', productId: 'prod-11', productName: 'Croissant Butter Classic', quantity: 1, unitPrice: 26000, subtotal: 26000 },
    ],
  },
  {
    // Siti Rahmawati — 20 Agu 2026, 14:26
    id: 'ord-102',
    invoiceNumber: 'INV-982102',
    customerName: 'Siti Rahmawati',
    paymentMethod: 'QRIS',
    subtotal: 54000,
    discountPercent: 0,
    discountAmount: 0,
    taxRatePercent: 11,
    taxAmount: 5940,
    totalAmount: 59940,
    paidAmount: 59940,
    changeAmount: 0,
    status: 'COMPLETED',
    createdAt: '2026-08-20T14:26:00+07:00',
    items: [
      { id: 'item-102-1', productId: 'prod-3', productName: 'Iced Caramel Macchiato', quantity: 1, unitPrice: 32000, subtotal: 32000 },
      { id: 'item-102-2', productId: 'prod-15', productName: 'Pisang Goreng Keju Cokelat Crispy', quantity: 1, unitPrice: 22000, subtotal: 22000 },
    ],
  },
  {
    // Budi Santoso — 19 Agu 2026, 19:26
    id: 'ord-103',
    invoiceNumber: 'INV-982103',
    customerName: 'Budi Santoso',
    paymentMethod: 'DEBIT',
    subtotal: 58000,
    discountPercent: 0,
    discountAmount: 0,
    taxRatePercent: 11,
    taxAmount: 6380,
    totalAmount: 64380,
    paidAmount: 64380,
    changeAmount: 0,
    status: 'COMPLETED',
    createdAt: '2026-08-19T19:26:00+07:00',
    items: [
      { id: 'item-103-1', productId: 'prod-7', productName: 'Matcha Latte Creamy Uji', quantity: 1, unitPrice: 30000, subtotal: 30000 },
      { id: 'item-103-2', productId: 'prod-8', productName: 'Iced Chocolate Hazelnut', quantity: 1, unitPrice: 28000, subtotal: 28000 },
    ],
  },
  {
    // Pelanggan Umum — 18 Agu 2026, 19:26
    id: 'ord-104',
    invoiceNumber: 'INV-982104',
    customerName: 'Pelanggan Umum',
    paymentMethod: 'CASH',
    subtotal: 47000,
    discountPercent: 0,
    discountAmount: 0,
    taxRatePercent: 11,
    taxAmount: 5170,
    totalAmount: 52170,
    paidAmount: 100000,
    changeAmount: 47830,
    status: 'COMPLETED',
    createdAt: '2026-08-18T19:26:00+07:00',
    items: [
      { id: 'item-104-1', productId: 'prod-14', productName: 'Crispy Croffle Caramel Glaze', quantity: 1, unitPrice: 25000, subtotal: 25000 },
      { id: 'item-104-2', productId: 'prod-16', productName: 'Fudgy Chocolate Brownie Almond', quantity: 1, unitPrice: 22000, subtotal: 22000 },
    ],
  },
  {
    // Dian Kusuma — 17 Agu 2026, 19:26
    id: 'ord-105',
    invoiceNumber: 'INV-982105',
    customerName: 'Dian Kusuma',
    paymentMethod: 'QRIS',
    subtotal: 90250,
    discountPercent: 0,
    discountAmount: 0,
    taxRatePercent: 11,
    taxAmount: 9928,
    totalAmount: 100178,
    paidAmount: 100178,
    changeAmount: 0,
    status: 'COMPLETED',
    createdAt: '2026-08-17T19:26:00+07:00',
    items: [
      { id: 'item-105-1', productId: 'prod-13', productName: 'Brewly Supreme Mix Platter', quantity: 1, unitPrice: 38000, subtotal: 38000 },
      { id: 'item-105-2', productId: 'prod-12', productName: 'Sandwich Smoked Beef & Cheese', quantity: 1, unitPrice: 36000, subtotal: 36000 },
    ],
  },
];

export const INITIAL_MEMBERS: CustomerMember[] = [
  { id: 'mem-1', name: 'Andi Pratama', phone: '081234567890', email: 'andi@gmail.com', discountPercent: 10, totalVisits: 1, createdAt: '2026-08-20' },
  { id: 'mem-2', name: 'Siti Rahmawati', phone: '081987654321', email: 'siti@gmail.com', discountPercent: 0, totalVisits: 1, createdAt: '2026-08-20' },
  { id: 'mem-3', name: 'Budi Santoso', phone: '085678901234', email: 'budi@gmail.com', discountPercent: 0, totalVisits: 1, createdAt: '2026-08-19' },
  { id: 'mem-4', name: 'Dian Kusuma', phone: '087812345678', email: 'dian@gmail.com', discountPercent: 0, totalVisits: 1, createdAt: '2026-08-17' },
];
